import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Intro from "../src/components/Intro";
import axios from "axios";
import TechStack from "../src/components/TechStack";
import Experience from "../src/components/Experience";
import { Education } from "../src/components/Education";
import { SimpleGrid, VStack, Box } from "@chakra-ui/react";
import ProjectCard from "../src/components/ProjectCard";
import Projects from "../src/components/Projects";
// import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data, data2 }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SimpleGrid columns={2}>
          <VStack>
            <Intro
              name={data.name}
              username={data.login}
              avatar={data.avatar_url}
              bio={data.bio}
            />
            <Experience />
            <TechStack />
            <Education />
          </VStack>
          <Box>
            <Projects data={data2} col={2} />
          </Box>
        </SimpleGrid>
      </main>
    </>
  );
}

export async function getStaticProps(context) {
  let response = await fetch(`https://api.github.com/users/bhav1kmaru`);
  let data = await response.json();
  let response2 = await fetch(
    `https://api.github.com/search/repositories?q=user:bhav1kmaru+fork:true&sort=updated&per_page=10&type=Repositories`
  );
  let data2 = await response2.json();
  return {
    props: {
      data,
      data2,
    },
  };
}

{
  /* <Intro name={data.name} username={data.login} avatar={data.avatar_url} bio={data.bio} />
       <TechStack />
       <Experience />
       <Education /> */
}
